services:
  rest-api:
    build: ./backend
    ports:
      - "8081:8081"
    networks:
      - app-network
  ui:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: galkaev
    depends_on:
      - postgres
    ports:
      - "9091:8080"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge