version: '3.8'

services:
  rest-api:
    build: ./backend
    ports:
      - "8081:8081"
    networks:
      - app-network
  ui:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
