services:
  rest-api:
    build: ./backend
    ports:
      - "8081:8081"
    networks:
      - app-network
  ui:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: paperless_postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Paperless123
    ports:
      - "5432:5432"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge