services:
  rest-api:
    build: ./backend
    ports:
      - "8081:8081"
    networks:
      - app-network
  ui:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: galkaev
    depends_on:
      - postgres
    ports:
      - "9091:8080"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4.0.3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"   # messaging
      - "9093:15672" # management UI
    networks:
      - app-network

  ocr-service:
    build: ./OCR
    environment:
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    networks:
      - app-network

  minio:
    image: quay.io/minio/minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    command: server /data --console-address ":9001"
   # volumes:
   #   - minio_data:/data
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.26 # latest open source version. after this version licensing was switched.
    environment:
      - discovery.type=single-node # uses single-node mode
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # limits the used memory to 512MB (chatGPT)
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.26
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge